---
abstract: 'Ensure Changes has content before releasing'
author:
  - 'David Golden <dagolden@cpan.org>'
  - 'Karen Etheridge <ether@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Cwd: 0
  Dist::Zilla::Tester: 0
  File::Find: 0
  File::Temp: 0
  Path::Class: 0
  Test::Harness: 0
  Test::More: 0.88
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120630'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-CheckChangesHasContent
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dist::Zilla::Plugin::CheckChangesHasContent:
    file: lib/Dist/Zilla/Plugin/CheckChangesHasContent.pm
    version: 0.005
  Dist::Zilla::Plugin::Test::ChangesHasContent:
    file: lib/Dist/Zilla/Plugin/Test/ChangesHasContent.pm
    version: 0.005
requires:
  Dist::Zilla: 2.100950
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Role::BeforeRelease: 0
  Dist::Zilla::Role::TextTemplate: 0
  File::pushd: 0
  Moose: 0.99
  autodie: 2.00
  namespace::autoclean: 0.09
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-CheckChangesHasContent
  homepage: https://github.com/dagolden/dist-zilla-plugin-checkchangeshascontent
  repository: https://github.com/dagolden/dist-zilla-plugin-checkchangeshascontent.git
version: 0.005
